version: "3"



services:
  ## ab http 服务
  web:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl/:/etc/nginx/conf.d/ssl
      - ./ab:/usr/share/nginx/app/ab
    ports:
      - 80:80
      - 443:443
    networks:
      - net

networks:
  net:
    driver: bridge