-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: Sample

local flatbuffers = require('flatbuffers')

local Monster_s2c = {} -- the module
local Monster_s2c_mt = {} -- the class metatable

function Monster_s2c.New()
    local o = {}
    setmetatable(o, {__index = Monster_s2c_mt})
    return o
end
function Monster_s2c.GetRootAsMonster_s2c(buf, offset)
    local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
    local o = Monster_s2c.New()
    o:Init(buf, n + offset)
    return o
end
function Monster_s2c_mt:Init(buf, pos)
    self.view = flatbuffers.view.New(buf, pos)
end
function Monster_s2c_mt:Pos()
    local o = self.view:Offset(4)
    if o ~= 0 then
        local x = o + self.view.pos
        local obj = require('common.Vec3').New()
        obj:Init(self.view.bytes, x)
        return obj
    end
end
function Monster_s2c_mt:Mana()
    local o = self.view:Offset(6)
    if o ~= 0 then
        return self.view:Get(flatbuffers.N.Int16, o + self.view.pos)
    end
    return 150
end
function Monster_s2c_mt:Hp()
    local o = self.view:Offset(8)
    if o ~= 0 then
        return self.view:Get(flatbuffers.N.Int16, o + self.view.pos)
    end
    return 100
end
function Monster_s2c_mt:Name()
    local o = self.view:Offset(10)
    if o ~= 0 then
        return self.view:String(o + self.view.pos)
    end
end
function Monster_s2c_mt:Inventory(j)
    local o = self.view:Offset(12)
    if o ~= 0 then
        local a = self.view:Vector(o)
        return self.view:Get(flatbuffers.N.Uint8, a + ((j-1) * 1))
    end
    return 0
end
function Monster_s2c_mt:InventoryLength()
    local o = self.view:Offset(12)
    if o ~= 0 then
        return self.view:VectorLen(o)
    end
    return 0
end
function Monster_s2c_mt:Color()
    local o = self.view:Offset(14)
    if o ~= 0 then
        return self.view:Get(flatbuffers.N.Int8, o + self.view.pos)
    end
    return 2
end
function Monster_s2c_mt:Weapons(j)
    local o = self.view:Offset(16)
    if o ~= 0 then
        local x = self.view:Vector(o)
        x = x + ((j-1) * 4)
        x = self.view:Indirect(x)
        local obj = require('common.Weapon').New()
        obj:Init(self.view.bytes, x)
        return obj
    end
end
function Monster_s2c_mt:WeaponsLength()
    local o = self.view:Offset(16)
    if o ~= 0 then
        return self.view:VectorLen(o)
    end
    return 0
end
function Monster_s2c_mt:EquippedType()
    local o = self.view:Offset(18)
    if o ~= 0 then
        return self.view:Get(flatbuffers.N.Uint8, o + self.view.pos)
    end
    return 0
end
function Monster_s2c_mt:Equipped()
    local o = self.view:Offset(20)
    if o ~= 0 then
        local obj = flatbuffers.view.New(require('flatbuffers.binaryarray').New(0), 0)
        self.view:Union(obj, o)
        return obj
    end
end
function Monster_s2c_mt:St()
    local o = self.view:Offset(22)
    if o ~= 0 then
        local x = self.view:Indirect(o + self.view.pos)
        local obj = require('Sample.shareT').New()
        obj:Init(self.view.bytes, x)
        return obj
    end
end
function Monster_s2c.Start(builder) builder:StartObject(10) end
function Monster_s2c.AddPos(builder, pos) builder:PrependStructSlot(0, pos, 0) end
function Monster_s2c.AddMana(builder, mana) builder:PrependInt16Slot(1, mana, 150) end
function Monster_s2c.AddHp(builder, hp) builder:PrependInt16Slot(2, hp, 100) end
function Monster_s2c.AddName(builder, name) builder:PrependUOffsetTRelativeSlot(3, name, 0) end
function Monster_s2c.AddInventory(builder, inventory) builder:PrependUOffsetTRelativeSlot(4, inventory, 0) end
function Monster_s2c.StartInventoryVector(builder, numElems) return builder:StartVector(1, numElems, 1) end
function Monster_s2c.AddColor(builder, color) builder:PrependInt8Slot(5, color, 2) end
function Monster_s2c.AddWeapons(builder, weapons) builder:PrependUOffsetTRelativeSlot(6, weapons, 0) end
function Monster_s2c.StartWeaponsVector(builder, numElems) return builder:StartVector(4, numElems, 4) end
function Monster_s2c.AddEquippedType(builder, equippedType) builder:PrependUint8Slot(7, equippedType, 0) end
function Monster_s2c.AddEquipped(builder, equipped) builder:PrependUOffsetTRelativeSlot(8, equipped, 0) end
function Monster_s2c.AddSt(builder, st) builder:PrependUOffsetTRelativeSlot(9, st, 0) end
function Monster_s2c.End(builder) return builder:EndObject() end

return Monster_s2c -- return the module