-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: common

local Equipment = {
    NONE = 0,
    Jewery = 1,
    Weapon = 2,
    Jewery2 = 3,
}

return Equipment -- return the module