-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: common

local flatbuffers = require('flatbuffers')

local Jewery2 = {} -- the module
local Jewery2_mt = {} -- the class metatable

function Jewery2.New()
    local o = {}
    setmetatable(o, {__index = Jewery2_mt})
    return o
end
function Jewery2.GetRootAsJewery2(buf, offset)
    local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
    local o = Jewery2.New()
    o:Init(buf, n + offset)
    return o
end
function Jewery2_mt:Init(buf, pos)
    self.view = flatbuffers.view.New(buf, pos)
end
function Jewery2_mt:Name()
    local o = self.view:Offset(4)
    if o ~= 0 then
        return self.view:String(o + self.view.pos)
    end
end
function Jewery2_mt:Damage()
    local o = self.view:Offset(6)
    if o ~= 0 then
        return self.view:Get(flatbuffers.N.Int16, o + self.view.pos)
    end
    return 0
end
function Jewery2.Start(builder) builder:StartObject(2) end
function Jewery2.AddName(builder, name) builder:PrependUOffsetTRelativeSlot(0, name, 0) end
function Jewery2.AddDamage(builder, damage) builder:PrependInt16Slot(1, damage, 0) end
function Jewery2.End(builder) return builder:EndObject() end

return Jewery2 -- return the module